version: v1.0
is_cypress: true
fail_fast: false
parallelism: 10
envs:
  - key: ENVIRONMENT
    value: review
  - key: BROWSER
    value: edge
triggers:
  - event: pull_request_labeled
    label: cypress-component-testing
global_job_config:
  setup:
    - checkout
    - neetoci-version node 16.16.0
    - cache restore
    - yarn install
    - cache store
  jobs:
    - name: Cypress
      commands:
        - yarn run cypress install
        - yarn cy:run:component
lifecycle:
  on_running:
    - action: remove_labels
      labels: ["cypress-component-testing"]
    - action: add_labels
      labels: ["cypress-triggered-component-testing"]

  on_complete:
    - action: remove_labels
      labels: ["cypress-triggered-component-testing"]
    - action: add_labels
      labels: ["cypress-completed-component-testing"]
