version: v1.0
is_cypress: true
fail_fast: false
parallelism: 10
envs:
  - key: CY_GROUP_SPEC
    value: "API|chrome|cypress/tests/api/*"
  - key: DEPLOYMENT_URL
    value: "http://localhost:3000"
triggers:
  - event: pull_request_labeled
    label: cypress-backend-testing
global_job_config:
  setup:
    - checkout
    - neetoci-version node 16.16.0
    - cache restore
    - echo $CY_GROUP_SPEC
    - CY_GROUP=$(echo $CY_GROUP_SPEC | cut -d'|' -f1)
    - CY_BROWSER=$(echo $CY_GROUP_SPEC | cut -d'|' -f2)
    - CY_SPEC=$(echo $CY_GROUP_SPEC | cut -d'|' -f3)
    - CY_CONFIG=$(echo $CY_GROUP_SPEC | cut -d'|' -f4)
    - echo $CY_GROUP
    - echo $CY_BROWSER
    - echo $CY_SPEC
    - echo $CY_CONFIG
    - yarn install
    - cache store --frozen-lockfile
  jobs:
    - name: Cypress
      commands:
        - yarn run cypress install
        - yarn build:ci
        - yarn start:ci & npx wait-on http://localhost:3000
        - npx cypress run --headless --parallel --record --key $RECORD_KEY --browser $CY_BROWSER --ci-build-id $CI_BUILD_ID --group "$CY_GROUP" --spec "$CY_SPEC" --config "$CY_CONFIG"
lifecycle:
  on_running:
    - action: remove_labels
      labels: ["cypress-backend-testing"]
    - action: add_labels
      labels: ["cypress-triggered-backend-testing"]

  on_complete:
    - action: remove_labels
      labels: ["cypress-triggered-backend-testing"]
    - action: add_labels
      labels: ["cypress-completed-backend-testing"]
